version: '3.8'

services:
  fastapi:
    container_name: lms--api
    build: ./
    command:  uvicorn lms.main:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-level debug --use-colors
    volumes:
      - ./server:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - lms__network
    restart: unless-stopped

  mongodb:
    container_name: lms--db
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
      - ./docker/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=christhoval
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      - MONGO_INITDB_DATABASE=loans
    networks:
      - lms__network

  mongo-express:
    image: mongo-express
    container_name: lms--mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=christhoval
      - ME_CONFIG_MONGODB_ADMINPASSWORD=S3cret
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - lms__network
    ports:
      - 8081:8081
    restart: unless-stopped

volumes:
  mongodb-data:
    name: mongodb-data

networks:
  lms__network:
    driver: bridge
