# fly.toml app configuration file generated for fastapi--lmss on 2023-07-27T07:51:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fastapi--lmss"
primary_region = "mia"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
